### ISSUE TITLE
access to ocean.pangeo.io

### ISSUE THREAD

**Issue by dcherian** [raphaeldussin/example.pangeo.io-deploy#11]
HI,

I'd like access to ocean.pangeo.io. I want to look at LLC4320 dataset on there.

**Comment by raphaeldussin** [comment]
Hi @dcherian ,

we're migrating the ocean.pangeo.io cluster. You can try staging.ocean.pangeo.io to test out things.
The new production cluster should be up and running shortly.

thanks for your patience,
Raf

**Comment by dcherian** [comment]
Awesome, thanks!
