### ISSUE TITLE
Access request for ocean.pangeo.io

### ISSUE THREAD

**Issue by michaeldenes** [raphaeldussin/example.pangeo.io-deploy#13]
Hi @raphaeldussin ,

Could I please get access to ocean.pangeo.io? I would like to use the llc4320 dataset in my work on finite-time coherent set identification.

Thanks,
Michael

**Comment by raphaeldussin** [comment]
Hi @michaeldenes 

Have you tried the "sign in with globus" button ?
it should ask you for your ORCID (https://orcid.org/) then let you in.
If you get an error, please copy/paste it here.

**Comment by michaeldenes** [comment]
Hi @raphaeldussin 
Apologies for the late response. I've successfully logged in using my ORCID. I'll close now.
Cheers, Michael.
