### ISSUE TITLE
Request access for lewismc to ocean.pangeo.io

### ISSUE THREAD

**Issue by lewismc** [raphaeldussin/example.pangeo.io-deploy#14]
Hi @raphaeldussin can you please grant me login access to ocean.pangeo.io. i would like to pursue the task of making NASA JPL PO.DAAC data available for use in Pangeo environment. 
Also, see https://github.com/pangeo-data/pangeo/issues/686 for more context on my larger goal.
Thank you

**Comment by rabernat** [comment]
Hi @lewismc -- this repo is a bit out of date. 

In order to access ocean.pangeo.io, you just need to make sure you have an ORCID account. Then you can just log on, no special permission needed.
