### ISSUE TITLE
"Build Recommended" message in jupyterlab

### ISSUE THREAD

**Issue by rabernat** [raphaeldussin/example.pangeo.io-deploy#2]
When I log in, I get the following message from jupyterlab.

> Build Recommended
JupyterLab build is suggested:
@jupyterlab/hub-extension needs to be included in build
@pyviz/jupyterlab_pyviz needs to be included in build
jupyter-leaflet needs to be included in build
@jupyter-widgets/jupyterlab-manager needs to be included in build
dask-labextension needs to be included in build

I seem to recall similar issues raised elsewhere in other deployments, but I can't track down a specific issue. Perhaps useful to coordinate with other cluster admins in https://github.com/pangeo-data/pangeo/issues/476.

![image](https://user-images.githubusercontent.com/1197350/48969360-8d21c400-efcb-11e8-9f10-f5ac45b9c077.png)

**Comment by raphaeldussin** [comment]
fixed by updating to dev.pangeo.io environment.yml file
