### ISSUE TITLE
holoview does not render images

### ISSUE THREAD

**Issue by raphaeldussin** [raphaeldussin/example.pangeo.io-deploy#3]
`Javascript Error: undefined is not an object (evaluating 'jQuery.ui')`

**Comment by rabernat** [comment]
Probably related to a package version. I really recommend starting from this environment:
https://github.com/rabernat/pangeo_ecco_examples/tree/master/binder

Which I believe can be more-or-less copied here:
https://github.com/raphaeldussin/example.pangeo.io-deploy/tree/staging/deployments/ocean.pangeo.io/image/binder

**Comment by raphaeldussin** [comment]
that's the next thing on my list. hopefully that will fix this too.

**Comment by raphaeldussin** [comment]
fixed by updating to dev.pangeo.io environment.yml file
